sonar.projectKey=bgp-ai-test-poc
sonar.projectName=bgp-ai-test-poc
sonar.projectVersion=1.0

sonar.sources=llm_runner.py,mcp_server,rag,utils,knowledge,topology.yaml
sonar.tests=tests,generated_scripts

sonar.exclusions=venv/**,.git/**,__pycache__/**,.pytest_cache/**,.ruff_cache/**,reports/**,rag/chroma_db/**
sonar.python.version=3.10
sonar.python.xunit.reportPath=reports/pytest-report.xml
sonar.python.coverage.reportPaths=reports/coverage.xml
